spira:
  service_account_user: anthony.ennis@hmhs.com
  proto: https
  host: highmarkhealth.spiraservice.net
  api-key: '{CF69015D-5208-4848-9E42-51CE9FA9CD7B}'
  username: anthony.ennis@hmhs.com
  service_instance: services/v6_0/RestService.svc
  polling:
    frequency: 10
    continuous: False
  artifact_ids:
    test_case: 2
    test_run: 5
  test_execution:
    test_pass: 2
    test_fail:
      - 1
      - 3
      - 4
      - 5
  custom_field_mappings:
    story_id: 6
    req_id: 7
  runtime:
    stop_on_error: True
    logging: True
  scope:
    project_scope: [28]
    requirement_type: "User Story"
    test_type: "manual"
digital:
  proto: https
  host: www16.v1host.com
  bearer: 'Bearer 1.VvzUpAo8PbdPEcbb2ol96VpcvfI='
  service_instance: api-examples
  story:
    status:
      accepted: 137
      in_progress: 134
      not_started: 133
      done: 135
  test:
    status:
      passId: 129
      failId: 155
mocks:
  spira:
    project:
      - 10
      - 20
